### ISSUE TITLE
Incorrect filenames cause issue

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/blob#21] opened 2018-02-12 13:52 UTC
## Example 1

I ended up with blob giving me this item in dir list for tenant s_hard001
path email/received

  {
    "name": "<VI1PR07MB3136EDCC918010CC857465B4F5560@VI1PR07MB3136.eurprd07.prod.outlook.com>",
    "extension": ".com>",
    "location": "/private/email/received",
    "path": "/private/email/received/<VI1PR07MB3136EDCC918010CC857465B4F5560@VI1PR07MB3136.eurprd07.prod.outlook.com>",
    "size": 0,
    "isFile": false,
    "isDirectory": false,
    "contentType": null,
    "checksum": null
  },

This is neither dir nor file !
Prevent creation of such or handle accordingly.

## Example 2

gr4per@dev-grapear1:~/duriel$ curl --header "$AUTH_HEADER" https://develop.businessnetwork.opuscapita.com/blob/api/c_ncc/files/public/c_ncc/onboarding/campaigns/eInvoiceSupplierOnboarding/1/ | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   822  100   822    0     0   2633      0 --:--:-- --:--:-- --:--:--  2634
[
  {
    "name": "2017-09-14%252010_42_50-Campaign%2520Editor.png",
    "extension": ".png",
    "location": "/public/c_ncc/onboarding/campaigns/eInvoiceSupplierOnboarding/1",
    "path": "/public/c_ncc/onboarding/campaigns/eInvoiceSupplierOnboarding/1/2017-09-14%252010_42_50-Campaign%2520Editor.png",
    "size": 28530,
    "isFile": true,
    "isDirectory": false,
    "lastModified": "2017-10-09T19:21:05.000Z",
    "contentType": "image/png",
    "checksum": "AhyxRUwBToES1XxvUYKUFw=="
  },
  {
    "name": "2017-10-06%252015_37_25-.png",
    "extension": ".png",
    "location": "/public/c_ncc/onboarding/campaigns/eInvoiceSupplierOnboarding/1",
    "path": "/public/c_ncc/onboarding/campaigns/eInvoiceSupplierOnboarding/1/2017-10-06%252015_37_25-.png",
    "size": 317453,
    "isFile": true,
    "isDirectory": false,
    "lastModified": "2017-10-09T19:21:13.000Z",
    "contentType": "image/png",
    "checksum": "tfeIdocl417dPEugvPgDUA=="
  }
]

BUT

gr4per@dev-grapear1:~/duriel$ curl --header "$AUTH_HEADER" https://develop.businessnetwork.opuscapita.com/blob/api/c_ncc/files/public/c_ncc/onboarding/campaigns/eInvoiceSupplierOnboarding/1/2017-09-14%252010_42_50-Campaign%2520Editor.png | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    47  100    47    0     0    287      0 --:--:-- --:--:-- --:--:--   288
{
  "message": "The requested file was not found."
}

**Comment by kwierchris** [comment] 2018-08-24 12:42
The first one is solved but can't reproduce the second one anymore even when using special characters and whitespaces. Closing.

**Closed by kwierchris** 2018-08-24 12:42 UTC
Labels: bug
